Update the model for LAAS-CNRS robot with camera by default.
agimus-project/franka_description pull request #2
Opened 2024-08-14 13:48 UTC by MaximilienNaveau

Hi @florent-lamiraux , @MedericFourmy , @Dorian-BAUDU,  @TheoMF 
I modified the model of the Panda to fit the specification of the "robot.urdf" that is found here:
- https://github.com/agimus-project/panda_torque_mpc/blob/main/urdf/robot.urdf
and here:
- https://github.com/agimus-project/agimus_controller/blob/main/urdf/robot.urdf

I will remove the model from both of the upper-mentioned packages in favor of the "official" agimus fork of the franka_description package.

The only unkown for me for now if how to handle the HPP model which if I am correct need a urdf with the full environment inside.
I believe that for HPP we will have to create a new xacro file in agimus_description that will contain the environment + the model of the robot.
@florent-lamiraux let me know your thoughts about this.

To whomever read this: Have a nice day!

2024-09-04 14:01 UTC, Kotochleb requested changes

2024-09-04 14:01 UTC, Kotochleb commented on robots/common/camera.xacro
In case this file stays as is I would opt to add some information that it is strongly based on the realsense URDF file. Just for legal reasons

2024-09-04 14:10 UTC, MaximilienNaveau commented on robots/common/camera.xacro
I am at my limit of knowledge here.
Could you provide a PR for this?
We can create an issue here in the mean time?

2024-09-05 13:18 UTC, Kotochleb approved these changes

2024-09-05 13:22 UTC, Kotochleb approved these changes
LGTM

2024-09-05 13:24 UTC, merged